services:
  rplay:
    container_name: rPlay
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /var/run:uid=101,gid=101,mode=755
      - /var/cache/nginx:uid=101,gid=101,mode=755
    volumes:
      - ./logs:/var/log/nginx
    restart: unless-stopped